name: notifiable_iterables
description: Provides iterables that implements the ChangeNotifier class.
version: 1.1.0
homepage: https://github.com/Cynnexis/notifiable_iterables
repository: https://github.com/Cynnexis/notifiable_iterables

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: 1.17.9
  dartdoc: 1.0.2

flutter:
