name: notifiable_iterables
description: Provides iterables that implements the ChangeNotifier class.
version: 1.0.0
homepage: https://github.com/Cynnexis/notifiable_iterables
repository: https://github.com/Cynnexis/notifiable_iterables
issue_tracker: https://github.com/Cynnexis/notifiable_iterables/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: 1.14.4
  dartdoc: 0.32.3

flutter:
